# config/zed2_yaml
# Parameters for Stereolabs ZED2 camera
---
/**:
  ros__parameters:
    general:
      camera_model: "zed2i"
      camera_name: "zed2i" # usually overwritten by launch file
      pub_resolution: "HD720"
      grab_resolution: "HD1080" # The native camera grab resolution. 'HD2K', 'HD1080', 'HD720', 'VGA', 'AUTO'
      grab_frame_rate: 20 # ZED SDK internal grabbing rate
      pub_frame_rate: 20.0 # publishing rate

    depth:
      min_depth: 0.2 # Min: 0.2, Max: 3.0
      max_depth: 2.0 # Max: 40.0
