# config/zed2_yaml
# Parameters for Stereolabs ZED2 camera
---
/**:
  ros__parameters:
    general:
      camera_model: "zed2i"
      camera_name: "zed2i" # usually overwritten by launch file
      pub_resolution: "HD2K"
      grab_resolution: "HD2K" # The native camera grab resolution. 'HD2K', 'HD1080', 'HD720', 'VGA', 'AUTO'
      grab_frame_rate: 15 # ZED SDK internal grabbing rate

    depth:
      min_depth: 0.2 # Min: 0.2, Max: 3.0
      max_depth: 40.0 # Max: 40.0
